import json
import os

sets_data = [
    {
        "id": 1,
        "name": "Classic 75-Ball Pub Bingo",
        "badge": "75 Balls",
        "theme": "classic",
        "type": "classic-75",
        "totalItems": 75,
        "description": "Traditional 75-ball pub bingo with authentic British & South African rhyming calls, nicknames, and pub jokes.",
        "icon": "fa-bowling-ball",
        "cardSize": 5,
        "hasFreeSpace": True,
        "items": [
            # B (1-15)
            {"id": 1, "col": "B", "call": "B-1", "title": "Kelly's Eye", "rhyme": "Kelly's Eye", "subtitle": "Number 1, the opening shot!"},
            {"id": 2, "col": "B", "call": "B-2", "title": "One Little Duck", "rhyme": "One Little Duck", "subtitle": "Quack quack, number 2"},
            {"id": 3, "col": "B", "call": "B-3", "title": "Cup of Tea", "rhyme": "Cup of Tea", "subtitle": "Warm brew, number 3"},
            {"id": 4, "col": "B", "call": "B-4", "title": "Knock at the Door", "rhyme": "Knock at the Door", "subtitle": "Who's there? Number 4"},
            {"id": 5, "col": "B", "call": "B-5", "title": "Man Alive", "rhyme": "Man Alive", "subtitle": "Look alive, number 5"},
            {"id": 6, "col": "B", "call": "B-6", "title": "Tom Mix", "rhyme": "Tom Mix / Half a Dozen", "subtitle": "In a fix with number 6"},
            {"id": 7, "col": "B", "call": "B-7", "title": "Lucky Seven", "rhyme": "Lucky Seven", "subtitle": "God's number, lucky 7"},
            {"id": 8, "col": "B", "call": "B-8", "title": "Garden Gate", "rhyme": "Garden Gate", "subtitle": "Meet me at the gate, number 8"},
            {"id": 9, "col": "B", "call": "B-9", "title": "Doctor's Orders", "rhyme": "Doctor's Orders", "subtitle": "Take your medicine, number 9"},
            {"id": 10, "col": "B", "call": "B-10", "title": "Uncle Ben", "rhyme": "Uncle Ben / Prime Minister's Den", "subtitle": "Big number 10"},
            {"id": 11, "col": "B", "call": "B-11", "title": "Legs Eleven", "rhyme": "Legs Eleven", "subtitle": "Wolf whistle! Number 11"},
            {"id": 12, "col": "B", "call": "B-12", "title": "One Dozen", "rhyme": "One Dozen", "subtitle": "A full baker's dozen minus one, 12"},
            {"id": 13, "col": "B", "call": "B-13", "title": "Unlucky for Some", "rhyme": "Unlucky for Some", "subtitle": "Black cat number 13"},
            {"id": 14, "col": "B", "call": "B-14", "title": "Valentine's Day", "rhyme": "Valentine's Day", "subtitle": "Fourteenth of February, 14"},
            {"id": 15, "col": "B", "call": "B-15", "title": "Young and Keen", "rhyme": "Young and Keen", "subtitle": "Fifteen, young and keen"},
            # I (16-30)
            {"id": 16, "col": "I", "call": "I-16", "title": "Sweet Sixteen", "rhyme": "Sweet Sixteen", "subtitle": "Never been kissed, 16"},
            {"id": 17, "col": "I", "call": "I-17", "title": "Dancing Queen", "rhyme": "Dancing Queen", "subtitle": "Feel the beat, 17"},
            {"id": 18, "col": "I", "call": "I-18", "title": "Coming of Age", "rhyme": "Coming of Age", "subtitle": "Key to the door soon, 18"},
            {"id": 19, "col": "I", "call": "I-19", "title": "Goodbye Teens", "rhyme": "Goodbye Teens", "subtitle": "Last of the teens, 19"},
            {"id": 20, "col": "I", "call": "I-20", "title": "One Score", "rhyme": "One Score", "subtitle": "Blind twenty, 20"},
            {"id": 21, "col": "I", "call": "I-21", "title": "Key of the Door", "rhyme": "Key of the Door / Royal Salute", "subtitle": "Finally independent, 21"},
            {"id": 22, "col": "I", "call": "I-22", "title": "Two Little Ducks", "rhyme": "Two Little Ducks", "subtitle": "Quack quack, 22"},
            {"id": 23, "col": "I", "call": "I-23", "title": "Thee and Me", "rhyme": "Thee and Me", "subtitle": "Just the two of us, 23"},
            {"id": 24, "col": "I", "call": "I-24", "title": "Two Dozen", "rhyme": "Two Dozen", "subtitle": "Double dozen, 24"},
            {"id": 25, "col": "I", "call": "I-25", "title": "Duck and Dive", "rhyme": "Duck and Dive", "subtitle": "Silver Jubilee, 25"},
            {"id": 26, "col": "I", "call": "I-26", "title": "Pick and Mix", "rhyme": "Pick and Mix", "subtitle": "Sweet shop, 26"},
            {"id": 27, "col": "I", "call": "I-27", "title": "Gateway to Heaven", "rhyme": "Gateway to Heaven", "subtitle": "Stairway climb, 27"},
            {"id": 28, "col": "I", "call": "I-28", "title": "In a State", "rhyme": "In a State / Overweight", "subtitle": "Too many beers, 28"},
            {"id": 29, "col": "I", "call": "I-29", "title": "Rise and Shine", "rhyme": "Rise and Shine", "subtitle": "Wakey wakey, 29"},
            {"id": 30, "col": "I", "call": "I-30", "title": "Dirty Gertie", "rhyme": "Dirty Gertie / Blind Thirty", "subtitle": "Flirty thirty, 30"},
            # N (31-45)
            {"id": 31, "col": "N", "call": "N-31", "title": "Get Up and Run", "rhyme": "Get Up and Run", "subtitle": "Sprint finish, 31"},
            {"id": 32, "col": "N", "call": "N-32", "title": "Buckle My Shoe", "rhyme": "Buckle My Shoe", "subtitle": "One two, 32"},
            {"id": 33, "col": "N", "call": "N-33", "title": "All the Threes", "rhyme": "All the Threes / Dirty Knee", "subtitle": "Fish and chips, 33"},
            {"id": 34, "col": "N", "call": "N-34", "title": "Ask for More", "rhyme": "Ask for More", "subtitle": "Oliver Twist, 34"},
            {"id": 35, "col": "N", "call": "N-35", "title": "Jump and Jive", "rhyme": "Jump and Jive", "subtitle": "Dancefloor classic, 35"},
            {"id": 36, "col": "N", "call": "N-36", "title": "Three Dozen", "rhyme": "Three Dozen", "subtitle": "Triple dozen, 36"},
            {"id": 37, "col": "N", "call": "N-37", "title": "More Than Eleven", "rhyme": "More Than Eleven", "subtitle": "Lucky streak, 37"},
            {"id": 38, "col": "N", "call": "N-38", "title": "Christmas Cake", "rhyme": "Christmas Cake", "subtitle": "Holiday treat, 38"},
            {"id": 39, "col": "N", "call": "N-39", "title": "39 Steps", "rhyme": "The 39 Steps", "subtitle": "Hitchcock classic, 39"},
            {"id": 40, "col": "N", "call": "N-40", "title": "Life Begins", "rhyme": "Life Begins at 40", "subtitle": "Naughty forty, 40"},
            {"id": 41, "col": "N", "call": "N-41", "title": "Time for Fun", "rhyme": "Time for Fun", "subtitle": "Party time, 41"},
            {"id": 42, "col": "N", "call": "N-42", "title": "Winnie the Pooh", "rhyme": "Winnie the Pooh", "subtitle": "Honey pot, 42"},
            {"id": 43, "col": "N", "call": "N-43", "title": "Down on Your Knees", "rhyme": "Down on Your Knees", "subtitle": "Say your prayers, 43"},
            {"id": 44, "col": "N", "call": "N-44", "title": "Droopy Drawers", "rhyme": "Droopy Drawers", "subtitle": "Pull 'em up, 44"},
            {"id": 45, "col": "N", "call": "N-45", "title": "Halfway There", "rhyme": "Halfway There", "subtitle": "Livin' on a prayer, 45"},
            # G (46-60)
            {"id": 46, "col": "G", "call": "G-46", "title": "Up to Tricks", "rhyme": "Up to Tricks", "subtitle": "Cheeky monkeys, 46"},
            {"id": 47, "col": "G", "call": "G-47", "title": "Four and Seven", "rhyme": "Four and Seven", "subtitle": "Almost fifty, 47"},
            {"id": 48, "col": "G", "call": "G-48", "title": "Four Dozen", "rhyme": "Four Dozen", "subtitle": "48 beers in two crates, 48"},
            {"id": 49, "col": "G", "call": "G-49", "title": "PC 49", "rhyme": "PC 49", "subtitle": "Old copper on patrol, 49"},
            {"id": 50, "col": "G", "call": "G-50", "title": "Half a Century", "rhyme": "Half a Century / Bullseye", "subtitle": "Golden jubilee, 50"},
            {"id": 51, "col": "G", "call": "G-51", "title": "Tweak of the Thumb", "rhyme": "Tweak of the Thumb", "subtitle": "Quick twist, 51"},
            {"id": 52, "col": "G", "call": "G-52", "title": "Danny La Rue", "rhyme": "Danny La Rue / Deck of Cards", "subtitle": "52 cards in a deck, 52"},
            {"id": 53, "col": "G", "call": "G-53", "title": "Here Comes Herbie", "rhyme": "Here Comes Herbie", "subtitle": "Love Bug 53"},
            {"id": 54, "col": "G", "call": "G-54", "title": "Clean the Floor", "rhyme": "Clean the Floor", "subtitle": "Mop it up, 54"},
            {"id": 55, "col": "G", "call": "G-55", "title": "Snakes Alive", "rhyme": "Snakes Alive", "subtitle": "Hissing double nickel, 55"},
            {"id": 56, "col": "G", "call": "G-56", "title": "Was She Worth It?", "rhyme": "Was She Worth It?", "subtitle": "Five shillings and sixpence, 56"},
            {"id": 57, "col": "G", "call": "G-57", "title": "Heinz Varieties", "rhyme": "Heinz Varieties", "subtitle": "Baked beans and tomato sauce, 57"},
            {"id": 58, "col": "G", "call": "G-58", "title": "Make Them Wait", "rhyme": "Make Them Wait", "subtitle": "Patience pays, 58"},
            {"id": 59, "col": "G", "call": "G-59", "title": "Brighton Line", "rhyme": "Brighton Line", "subtitle": "Express train, 59"},
            {"id": 60, "col": "G", "call": "G-60", "title": "Five Dozen", "rhyme": "Five Dozen / Grandma's Frisky", "subtitle": "Three score, 60"},
            # O (61-75)
            {"id": 61, "col": "O", "call": "O-61", "title": "Baker's Bun", "rhyme": "Baker's Bun", "subtitle": "Fresh from the oven, 61"},
            {"id": 62, "col": "O", "call": "O-62", "title": "Turn the Screw", "rhyme": "Turn the Screw", "subtitle": "Tighten up, 62"},
            {"id": 63, "col": "O", "call": "O-63", "title": "Tickle Me", "rhyme": "Tickle Me", "subtitle": "Giggle time, 63"},
            {"id": 64, "col": "O", "call": "O-64", "title": "Red Raw", "rhyme": "Red Raw", "subtitle": "Too much sun, 64"},
            {"id": 65, "col": "O", "call": "O-65", "title": "Old Age Pension", "rhyme": "Old Age Pension", "subtitle": "Time to put feet up, 65"},
            {"id": 66, "col": "O", "call": "O-66", "title": "Clickety Click", "rhyme": "Clickety Click", "subtitle": "Route 66, 66"},
            {"id": 67, "col": "O", "call": "O-67", "title": "Stairway to Heaven", "rhyme": "Stairway to Heaven", "subtitle": "Led Zeppelin guitar riff, 67"},
            {"id": 68, "col": "O", "call": "O-68", "title": "Saving Grace", "rhyme": "Saving Grace / Pick a Mate", "subtitle": "Almost seventy, 68"},
            {"id": 69, "col": "O", "call": "O-69", "title": "Either Way Up", "rhyme": "Either Way Up / Any Way Up", "subtitle": "Ooh err! Number 69"},
            {"id": 70, "col": "O", "call": "O-70", "title": "Three Score and Ten", "rhyme": "Three Score and Ten", "subtitle": "Blind seventy, 70"},
            {"id": 71, "col": "O", "call": "O-71", "title": "Bang on the Drum", "rhyme": "Bang on the Drum", "subtitle": "Keep the beat, 71"},
            {"id": 72, "col": "O", "call": "O-72", "title": "Six Dozen", "rhyme": "Six Dozen / A Crutch and a Duck", "subtitle": "Halfway to gross, 72"},
            {"id": 73, "col": "O", "call": "O-73", "title": "Queen Bee", "rhyme": "Queen Bee", "subtitle": "Sweet honey buzz, 73"},
            {"id": 74, "col": "O", "call": "O-74", "title": "Candy Store", "rhyme": "Candy Store", "subtitle": "Lollipops and treats, 74"},
            {"id": 75, "col": "O", "call": "O-75", "title": "Top of the 75", "rhyme": "Strive and Strive / Top of the 75", "subtitle": "Last ball of the cage, 75"}
        ]
    },
    {
        "id": 2,
        "name": "90-Ball Traditional Pub & Club Bingo",
        "badge": "90 Balls",
        "theme": "pub-90",
        "type": "traditional-90",
        "totalItems": 90,
        "description": "Full 90-ball British & South African pub and clubhouse bingo with traditional 3x9 strip tickets and rhyming calls.",
        "icon": "fa-dice",
        "cardSize": 9,
        "hasFreeSpace": False,
        "items": [] # Generated programmatically below (1-90)
    }
]

# Populate Set 2 with 1-90 items
rhymes_90 = {
    76: ("Trombones", "76 Trombones led the big parade"),
    77: ("Sunset Strip", "Sunset Strip / Two Little Crutches, 77"),
    78: ("Heavens Above", "Look to the sky, 78"),
    79: ("One More Time", "Encore, 79"),
    80: ("Gandhi's Breakfast", "Eight and blank, 80"),
    81: ("Fat Lady with a Stick", "Stop and run, 81"),
    82: ("Straight On Through", "Clear road, 82"),
    83: ("Time for Tea", "Kettle on, 83"),
    84: ("Seven Dozen", "Seven full dozen, 84"),
    85: ("Staying Alive", "Bee Gees disco, 85"),
    86: ("Between the Sticks", "Goalkeeper alert, 86"),
    87: ("Torquay in Devon", "English seaside, 87"),
    88: ("Two Fat Ladies", "Wobble wobble, 88"),
    89: ("Nearly There", "One away from the top, 89"),
    90: ("Top of the Shop", "End of the line, 90")
}

for i in range(1, 91):
    col_idx = (i - 1) // 10
    col_names = ["1-9", "10-19", "20-29", "30-39", "40-49", "50-59", "60-69", "70-79", "80-90"]
    col_str = col_names[min(col_idx, 8)]
    if i <= 75:
        match_item = sets_data[0]["items"][i - 1]
        sets_data[1]["items"].append({
            "id": i,
            "col": col_str,
            "call": str(i),
            "title": match_item["title"],
            "rhyme": match_item["rhyme"],
            "subtitle": match_item["subtitle"]
        })
    else:
        title, sub = rhymes_90[i]
        sets_data[1]["items"].append({
            "id": i,
            "col": col_str,
            "call": str(i),
            "title": title,
            "rhyme": title,
            "subtitle": sub
        })

# Music & Themed Sets Helper
cols_75 = ["B"] * 15 + ["I"] * 15 + ["N"] * 15 + ["G"] * 15 + ["O"] * 15

def make_music_set(set_id, name, badge, theme, desc, icon, tracks):
    items = []
    for idx, t in enumerate(tracks):
        num = idx + 1
        col = cols_75[idx]
        artist = t["artist"]
        song = t["song"]
        year = t.get("year", "")
        hint = t.get("hint", "")
        items.append({
            "id": num,
            "col": col,
            "call": f"{col}-{num}",
            "title": song,
            "artist": artist,
            "year": year,
            "subtitle": f"{artist} ({year})" if year else artist,
            "rhyme": f"{artist} - {song}",
            "hint": hint
        })
    return {
        "id": set_id,
        "name": name,
        "badge": badge,
        "theme": theme,
        "type": "music-75",
        "totalItems": 75,
        "description": desc,
        "icon": icon,
        "cardSize": 5,
        "hasFreeSpace": True,
        "items": items
    }

# 80s Rock & Pop Hits (75 Tracks)
tracks_80s = [
    # B: 1-15
    {"artist": "Queen", "song": "Another One Bites the Dust", "year": "1980", "hint": "And another one gone, and another one gone"},
    {"artist": "Bon Jovi", "song": "Livin' on a Prayer", "year": "1986", "hint": "Tommy used to work on the docks..."},
    {"artist": "Michael Jackson", "song": "Billie Jean", "year": "1982", "hint": "The kid is not my son..."},
    {"artist": "Whitney Houston", "song": "I Wanna Dance with Somebody", "year": "1987", "hint": "Feel the heat with somebody"},
    {"artist": "Journey", "song": "Don't Stop Believin'", "year": "1981", "hint": "Just a small-town girl, livin' in a lonely world"},
    {"artist": "Guns N' Roses", "song": "Sweet Child O' Mine", "year": "1987", "hint": "She's got eyes of the bluest skies"},
    {"artist": "Toto", "song": "Africa", "year": "1982", "hint": "I bless the rains down in Africa"},
    {"artist": "Cyndi Lauper", "song": "Girls Just Want to Have Fun", "year": "1983", "hint": "I come home in the morning light"},
    {"artist": "Wham!", "song": "Wake Me Up Before You Go-Go", "year": "1984", "hint": "Don't leave me hanging on like a yo-yo"},
    {"artist": "Def Leppard", "song": "Pour Some Sugar on Me", "year": "1987", "hint": "In the name of love!"},
    {"artist": "Rick Astley", "song": "Never Gonna Give You Up", "year": "1987", "hint": "Never gonna let you down"},
    {"artist": "Prince", "song": "Purple Rain", "year": "1984", "hint": "Only wanted to see you underneath the purple rain"},
    {"artist": "Bryan Adams", "song": "Summer of '69", "year": "1984", "hint": "I got my first real six-string"},
    {"artist": "a-ha", "song": "Take On Me", "year": "1985", "hint": "I'll be gone in a day or two"},
    {"artist": "Madonna", "song": "Like a Prayer", "year": "1989", "hint": "Life is a mystery, everyone must stand alone"},
    # I: 16-30
    {"artist": "Survivor", "song": "Eye of the Tiger", "year": "1982", "hint": "Rising up, back on the street"},
    {"artist": "The Police", "song": "Every Breath You Take", "year": "1983", "hint": "Every move you make, I'll be watching you"},
    {"artist": "Kenny Loggins", "song": "Footloose", "year": "1984", "hint": "Kick off your Sunday shoes"},
    {"artist": "Europe", "song": "The Final Countdown", "year": "1986", "hint": "We're leaving together, but still it's farewell"},
    {"artist": "Van Halen", "song": "Jump", "year": "1984", "hint": "Might as well jump!"},
    {"artist": "Duran Duran", "song": "Hungry Like the Wolf", "year": "1982", "hint": "Dark in the city, night is a wire"},
    {"artist": "Eurythmics", "song": "Sweet Dreams (Are Made of This)", "year": "1983", "hint": "Who am I to disagree?"},
    {"artist": "Dexys Midnight Runners", "song": "Come On Eileen", "year": "1982", "hint": "At this moment you mean everything"},
    {"artist": "Tears for Fears", "song": "Everybody Wants to Rule the World", "year": "1985", "hint": "Welcome to your life, there's no turning back"},
    {"artist": "Phil Collins", "song": "In the Air Tonight", "year": "1981", "hint": "Legendary drum fill of all time"},
    {"artist": "AC/DC", "song": "You Shook Me All Night Long", "year": "1980", "hint": "She was a fast machine, kept her motor clean"},
    {"artist": "Lionel Richie", "song": "All Night Long", "year": "1983", "hint": "Fiesta, forever, come on and sing along"},
    {"artist": "David Bowie", "song": "Let's Dance", "year": "1983", "hint": "Put on your red shoes and dance the blues"},
    {"artist": "Men at Work", "song": "Down Under", "year": "1981", "hint": "Where beer does flow and men chunder"},
    {"artist": "U2", "song": "With or Without You", "year": "1987", "hint": "I can't live with or without you"},
    # N: 31-45
    {"artist": "Joan Jett", "song": "I Love Rock 'n Roll", "year": "1981", "hint": "So put another dime in the jukebox baby"},
    {"artist": "Simple Minds", "song": "Don't You (Forget About Me)", "year": "1985", "hint": "The Breakfast Club anthem"},
    {"artist": "Billy Joel", "song": "Uptown Girl", "year": "1983", "hint": "She's been living in her white-bread world"},
    {"artist": "Starship", "song": "We Built This City", "year": "1985", "hint": "We built this city on rock and roll"},
    {"artist": "Bonnie Tyler", "song": "Total Eclipse of the Heart", "year": "1983", "hint": "Turn around, every now and then I get a little bit lonely"},
    {"artist": "Run-D.M.C. & Aerosmith", "song": "Walk This Way", "year": "1986", "hint": "Talk this way!"},
    {"artist": "The Clash", "song": "Should I Stay or Should I Go", "year": "1982", "hint": "If I go there will be trouble, and if I stay it will be double"},
    {"artist": "Bruce Springsteen", "song": "Born in the U.S.A.", "year": "1984", "hint": "I was born in a small town..."},
    {"artist": "George Michael", "song": "Faith", "year": "1987", "hint": "Well I guess it would be nice if I could touch your body"},
    {"artist": "Soft Cell", "song": "Tainted Love", "year": "1981", "hint": "Sometimes I feel I've got to run away"},
    {"artist": "The Cure", "song": "Just Like Heaven", "year": "1987", "hint": "Show me how you do that trick"},
    {"artist": "Blondie", "song": "Call Me", "year": "1980", "hint": "Colour me your colour, baby"},
    {"artist": "Poison", "song": "Every Rose Has Its Thorn", "year": "1988", "hint": "Just like every night has its dawn"},
    {"artist": "Katrina and the Waves", "song": "Walking on Sunshine", "year": "1985", "hint": "And don't it feel good!"},
    {"artist": "Whitesnake", "song": "Here I Go Again", "year": "1987", "hint": "Like a drifter I was born to walk alone"},
    # G: 46-60
    {"artist": "Earth, Wind & Fire", "song": "Let's Groove", "year": "1981", "hint": "Let's groove tonight, share the spice of life"},
    {"artist": "The Bangles", "song": "Walk Like an Egyptian", "year": "1986", "hint": "All the old paintings on the tomb"},
    {"artist": "Dead or Alive", "song": "You Spin Me Round (Like a Record)", "year": "1984", "hint": "Right round round round"},
    {"artist": "Frankie Goes to Hollywood", "song": "Relax", "year": "1983", "hint": "Don't do it, when you want to suck it to it"},
    {"artist": "Foreigner", "song": "I Want to Know What Love Is", "year": "1984", "hint": "I want you to show me"},
    {"artist": "Stevie Wonder", "song": "I Just Called to Say I Love You", "year": "1984", "hint": "No New Year's Day to celebrate"},
    {"artist": "Tina Turner", "song": "The Best", "year": "1989", "hint": "Simply the best, better than all the rest"},
    {"artist": "Rick James", "song": "Super Freak", "year": "1981", "hint": "She's a very kinky girl"},
    {"artist": "Billy Ocean", "song": "Caribbean Queen", "year": "1984", "hint": "Now we're sharing the same dream"},
    {"artist": "Belinda Carlisle", "song": "Heaven Is a Place on Earth", "year": "1987", "hint": "Ooh baby, do you know what that's worth?"},
    {"artist": "Cutting Crew", "song": "(I Just) Died in Your Arms", "year": "1986", "hint": "It must have been something you said"},
    {"artist": "Roxette", "song": "The Look", "year": "1988", "hint": "She's got the look!"},
    {"artist": "Fine Young Cannibals", "song": "She Drives Me Crazy", "year": "1988", "hint": "Like no one else"},
    {"artist": "Chaka Khan", "song": "Ain't Nobody", "year": "1983", "hint": "Loves me better, makes me happy"},
    {"artist": "Scorpions", "song": "Wind of Change", "year": "1989", "hint": "Follow the Moskva down to Gorky Park"},
    # O: 61-75
    {"artist": "INXS", "song": "Need You Tonight", "year": "1987", "hint": "All you got is this moment"},
    {"artist": "Pet Shop Boys", "song": "West End Girls", "year": "1984", "hint": "In a town, in a strange town"},
    {"artist": "Laura Branigan", "song": "Gloria", "year": "1982", "hint": "Calling Gloria, don't you think you're falling?"},
    {"artist": "Culture Club", "song": "Karma Chameleon", "year": "1983", "hint": "You come and go, you come and go"},
    {"artist": "Spandau Ballet", "song": "True", "year": "1983", "hint": "This is the sound of my soul"},
    {"artist": "Rick Springfield", "song": "Jessie's Girl", "year": "1981", "hint": "I wish that I had Jessie's girl"},
    {"artist": "Bananarama", "song": "Venus", "year": "1986", "hint": "I'm your Venus, I'm your fire"},
    {"artist": "Level 42", "song": "Lessons in Love", "year": "1986", "hint": "We are getting nowhere"},
    {"artist": "Talk Talk", "song": "It's My Life", "year": "1984", "hint": "Don't you forget it"},
    {"artist": "Twisted Sister", "song": "We're Not Gonna Take It", "year": "1984", "hint": "No, we ain't gonna take it anymore!"},
    {"artist": "Simple Minds", "song": "Alive and Kicking", "year": "1985", "hint": "What you gonna do when things go wrong?"},
    {"artist": "Hall & Oates", "song": "Maneater", "year": "1982", "hint": "Watch out boy, she'll chew you up"},
    {"artist": "Ray Parker Jr.", "song": "Ghostbusters", "year": "1984", "hint": "Who you gonna call?"},
    {"artist": "Baltimora", "song": "Tarzan Boy", "year": "1985", "hint": "Oh-oh-oh-oh-oh-oh-oh-oh-oh-oh-oh"},
    {"artist": "Queen", "song": "Radio Ga Ga", "year": "1984", "hint": "All we hear is radio ga ga, radio goo goo"}
]
sets_data.append(make_music_set(3, "80s Rock & Pop Hits Music Bingo", "80s Music", "music-80s", "Classic synth-pop, rock bangers, and legendary radio gold from the 1980s.", "fa-compact-disc", tracks_80s))

# 90s Dance, Pop & Singalongs (75 Tracks)
tracks_90s = [
    # B: 1-15
    {"artist": "Spice Girls", "song": "Wannabe", "year": "1996", "hint": "If you wanna be my lover"},
    {"artist": "Backstreet Boys", "song": "Everybody (Backstreet's Back)", "year": "1997", "hint": "Backstreet's back, alright!"},
    {"artist": "Oasis", "song": "Wonderwall", "year": "1995", "hint": "Today is gonna be the day that they're gonna throw it back to you"},
    {"artist": "TLC", "song": "No Scrubs", "year": "1999", "hint": "A scrub is a guy that thinks he's fly"},
    {"artist": "Britney Spears", "song": "...Baby One More Time", "year": "1998", "hint": "My loneliness is killing me"},
    {"artist": "Cher", "song": "Believe", "year": "1998", "hint": "Do you believe in life after love?"},
    {"artist": "Nirvana", "song": "Smells Like Teen Spirit", "year": "1991", "hint": "With the lights out, it's less dangerous"},
    {"artist": "Ricky Martin", "song": "Livin' la Vida Loca", "year": "1999", "hint": "She's into superstitions, black cats and voodoo dolls"},
    {"artist": "Hanson", "song": "MMMBop", "year": "1997", "hint": "Ba du bop, ba duba dop"},
    {"artist": "Goo Goo Dolls", "song": "Iris", "year": "1998", "hint": "And I'd give up forever to touch you"},
    {"artist": "Fatboy Slim", "song": "Praise You", "year": "1998", "hint": "We've come a long, long way together"},
    {"artist": "Aqua", "song": "Barbie Girl", "year": "1997", "hint": "Life in plastic, it's fantastic!"},
    {"artist": "Smash Mouth", "song": "All Star", "year": "1999", "hint": "Somebody once told me the world is gonna roll me"},
    {"artist": "Green Day", "song": "Basket Case", "year": "1994", "hint": "Do you have the time to listen to me whine?"},
    {"artist": "Blink-182", "song": "All the Small Things", "year": "1999", "hint": "Say it ain't so, I will not go"},
    # I: 16-30
    {"artist": "Lou Bega", "song": "Mambo No. 5", "year": "1999", "hint": "A little bit of Monica in my life"},
    {"artist": "MC Hammer", "song": "U Can't Touch This", "year": "1990", "hint": "Stop! Hammer time!"},
    {"artist": "Vanilla Ice", "song": "Ice Ice Baby", "year": "1990", "hint": "Alright stop, collaborate and listen"},
    {"artist": "Ace of Base", "song": "All That She Wants", "year": "1992", "hint": "Is another baby, she's gone tomorrow boy"},
    {"artist": "Haddaway", "song": "What Is Love", "year": "1993", "hint": "Baby don't hurt me, don't hurt me no more"},
    {"artist": "SNAP!", "song": "Rhythm Is a Dancer", "year": "1992", "hint": "It's a soul's companion, people feel it everywhere"},
    {"artist": "Corona", "song": "The Rhythm of the Night", "year": "1993", "hint": "This is the rhythm of my life"},
    {"artist": "Eiffel 65", "song": "Blue (Da Ba Dee)", "year": "1998", "hint": "I have a blue house with a blue window"},
    {"artist": "Vengaboys", "song": "Boom, Boom, Boom, Boom!!", "year": "1998", "hint": "I want you in my room"},
    {"artist": "Shania Twain", "song": "Man! I Feel Like a Woman!", "year": "1997", "hint": "Let's go girls!"},
    {"artist": "Red Hot Chili Peppers", "song": "Under the Bridge", "year": "1991", "hint": "Sometimes I feel like I don't have a partner"},
    {"artist": "Natalie Imbruglia", "song": "Torn", "year": "1997", "hint": "I'm all out of faith, this is how I feel"},
    {"artist": "The Rembrandts", "song": "I'll Be There for You", "year": "1994", "hint": "So no one told you life was gonna be this way"},
    {"artist": "No Doubt", "song": "Don't Speak", "year": "1995", "hint": "I know just what you're saying"},
    {"artist": "4 Non Blondes", "song": "What's Up?", "year": "1992", "hint": "And I say: HEY-YEY-YEY-YEY"},
    # N: 31-45
    {"artist": "The Cranberries", "song": "Zombie", "year": "1994", "hint": "In your head, in your head, Zombie, zombie"},
    {"artist": "Savage Garden", "song": "Truly Madly Deeply", "year": "1997", "hint": "I'll be your dream, I'll be your wish"},
    {"artist": "Santana ft. Rob Thomas", "song": "Smooth", "year": "1999", "hint": "Man, it's a hot one, like seven inches from the midday sun"},
    {"artist": "Will Smith", "song": "Gettin' Jiggy wit It", "year": "1997", "hint": "Na na na na na na na"},
    {"artist": "Eagle-Eye Cherry", "song": "Save Tonight", "year": "1997", "hint": "Fight the break of dawn, come tomorrow tomorrow I'll be gone"},
    {"artist": "Spin Doctors", "song": "Two Princes", "year": "1991", "hint": "One has diamonds in his pockets"},
    {"artist": "Chumbawamba", "song": "Tubthumping", "year": "1997", "hint": "I get knocked down, but I get up again"},
    {"artist": "Coolio", "song": "Gangsta's Paradise", "year": "1995", "hint": "As I walk through the valley of the shadow of death"},
    {"artist": "Sir Mix-a-Lot", "song": "Baby Got Back", "year": "1992", "hint": "I like big butts and I cannot lie"},
    {"artist": "Cardigans", "song": "Lovefool", "year": "1996", "hint": "Love me love me, say that you love me"},
    {"artist": "Sixpence None the Richer", "song": "Kiss Me", "year": "1997", "hint": "Kiss me out of the bearded barley"},
    {"artist": "Fugees", "song": "Killing Me Softly", "year": "1996", "hint": "Strumming my pain with his fingers"},
    {"artist": "Destiny's Child", "song": "Say My Name", "year": "1999", "hint": "If no one is around you, say baby I love you"},
    {"artist": "Len", "song": "Steal My Sunshine", "year": "1999", "hint": "I know it's up for me"},
    {"artist": "Third Eye Blind", "song": "Semi-Charmed Life", "year": "1997", "hint": "Doo doo doo, doo doo-doo doo"},
    # G: 46-60
    {"artist": "The Proclaimers", "song": "I'm Gonna Be (500 Miles)", "year": "1993", "hint": "And I would walk 500 miles"},
    {"artist": "Scatman John", "song": "Scatman (Ski-Ba-Bop-Ba-Dop-Bop)", "year": "1994", "hint": "Ski-ba-bop-ba-dop-bop"},
    {"artist": "Reel 2 Real", "song": "I Like to Move It", "year": "1993", "hint": "You like to move it move it!"},
    {"artist": "R.E.M.", "song": "Losing My Religion", "year": "1991", "hint": "That's me in the corner, that's me in the spotlight"},
    {"artist": "Alanis Morissette", "song": "Ironic", "year": "1995", "hint": "It's like rain on your wedding day"},
    {"artist": "Seal", "song": "Kiss from a Rose", "year": "1994", "hint": "There used to be a greying tower alone on the sea"},
    {"artist": "C&C Music Factory", "song": "Gonna Make You Sweat (Everybody Dance Now)", "year": "1990", "hint": "Everybody dance now!"},
    {"artist": "En Vogue", "song": "My Lovin' (You're Never Gonna Get It)", "year": "1992", "hint": "Free your mind and the rest will follow"},
    {"artist": "House of Pain", "song": "Jump Around", "year": "1992", "hint": "Pack it up, pack it in, let me begin"},
    {"artist": "Montell Jordan", "song": "This Is How We Do It", "year": "1995", "hint": "It's Friday night, and I feel alright"},
    {"artist": "Barenaked Ladies", "song": "One Week", "year": "1998", "hint": "It's been one week since you looked at me"},
    {"artist": "UB40", "song": "Can't Help Falling in Love", "year": "1993", "hint": "Wise men say only fools rush in"},
    {"artist": "Boyz II Men", "song": "End of the Road", "year": "1992", "hint": "Although we've come to the end of the road"},
    {"artist": "TLC", "song": "Waterfalls", "year": "1994", "hint": "Don't go chasing waterfalls"},
    {"artist": "New Radicals", "song": "You Get What You Give", "year": "1998", "hint": "Don't let go, one two, you got the music in you"},
    # O: 61-75
    {"artist": "Daft Punk", "song": "Around the World", "year": "1997", "hint": "Around the world, around the world"},
    {"artist": "Alice Deejay", "song": "Better Off Alone", "year": "1998", "hint": "Do you think you're better off alone?"},
    {"artist": "Gala", "song": "Freed from Desire", "year": "1996", "hint": "Mind and senses purified, freed from desire"},
    {"artist": "Whigfield", "song": "Saturday Night", "year": "1994", "hint": "Dee dee na na na, Saturday night"},
    {"artist": "Crystal Waters", "song": "Gypsy Woman (She's Homeless)", "year": "1991", "hint": "La da dee, la da da"},
    {"artist": "Ace of Base", "song": "The Sign", "year": "1993", "hint": "I saw the sign and it opened up my eyes"},
    {"artist": "Londonbeat", "song": "I've Been Thinking About You", "year": "1990", "hint": "I've been thinking about you, in the shadows of my mind"},
    {"artist": "Bloodhound Gang", "song": "The Bad Touch", "year": "1999", "hint": "You and me baby ain't nothin' but mammals"},
    {"artist": "Robbie Williams", "song": "Angels", "year": "1997", "hint": "And through it all, she offers me protection"},
    {"artist": "Faithless", "song": "Insomnia", "year": "1995", "hint": "I can't get no sleep"},
    {"artist": "Blur", "song": "Song 2", "year": "1997", "hint": "Woo-hoo! When I feel heavy-metal"},
    {"artist": "Radiohead", "song": "Creep", "year": "1992", "hint": "I'm a creep, I'm a weirdo"},
    {"artist": "Counting Crows", "song": "Mr. Jones", "year": "1993", "hint": "Mr. Jones and me talking about the future"},
    {"artist": "Silverchair", "song": "Tomorrow", "year": "1994", "hint": "You wait till tomorrow"},
    {"artist": "Crash Test Dummies", "song": "Mmm Mmm Mmm Mmm", "year": "1993", "hint": "Once there was this boy who..."}
]
sets_data.append(make_music_set(4, "90s Dance, Pop & Singalongs", "90s Party", "music-90s", "Eurodance, boybands, britpop, and feel-good party anthems of the 1990s.", "fa-radio", tracks_90s))

# 2000s Pop & Party Anthems (75 Tracks)
tracks_2000s = [
    # B: 1-15
    {"artist": "Outkast", "song": "Hey Ya!", "year": "2003", "hint": "Shake it like a Polaroid picture"},
    {"artist": "Eminem", "song": "Lose Yourself", "year": "2002", "hint": "His palms are sweaty, knees weak, arms are heavy"},
    {"artist": "Beyoncé ft. Jay-Z", "song": "Crazy in Love", "year": "2003", "hint": "Got me looking so crazy in love"},
    {"artist": "The Black Eyed Peas", "song": "I Gotta Feeling", "year": "2009", "hint": "Tonight's gonna be a good night"},
    {"artist": "Shakira ft. Wyclef Jean", "song": "Hips Don't Lie", "year": "2006", "hint": "I never really knew that she could dance like this"},
    {"artist": "The Killers", "song": "Mr. Brightside", "year": "2004", "hint": "Coming out of my cage and I've been doing just fine"},
    {"artist": "Rihanna ft. Jay-Z", "song": "Umbrella", "year": "2007", "hint": "Under my umbrella, ella, ella, eh, eh"},
    {"artist": "Usher ft. Lil Jon & Ludacris", "song": "Yeah!", "year": "2004", "hint": "Peace up, A-Town down!"},
    {"artist": "Coldplay", "song": "Viva la Vida", "year": "2008", "hint": "I used to rule the world, seas would rise when I gave the word"},
    {"artist": "Maroon 5", "song": "This Love", "year": "2002", "hint": "This love has taken its toll on me"},
    {"artist": "Nelly", "song": "Hot in Herre", "year": "2002", "hint": "It's getting hot in here, so take off all your clothes"},
    {"artist": "Justin Timberlake", "song": "SexyBack", "year": "2006", "hint": "I'm bringing sexy back, them other boys don't know how to act"},
    {"artist": "Kelly Clarkson", "song": "Since U Been Gone", "year": "2004", "hint": "Since you been gone, I can breathe for the first time"},
    {"artist": "Lady Gaga", "song": "Poker Face", "year": "2008", "hint": "Can't read my, can't read my, no he can't read my poker face"},
    {"artist": "Linkin Park", "song": "In the End", "year": "2000", "hint": "I tried so hard and got so far"},
    # I: 16-30
    {"artist": "Katy Perry", "song": "Hot N Cold", "year": "2008", "hint": "You change your mind like a girl changes clothes"},
    {"artist": "Fall Out Boy", "song": "Sugar, We're Goin Down", "year": "2005", "hint": "We're going down down in an earlier round"},
    {"artist": "Gwen Stefani", "song": "Hollaback Girl", "year": "2004", "hint": "Ain't no hollaback girl, B-A-N-A-N-A-S"},
    {"artist": "Gnarls Barkley", "song": "Crazy", "year": "2006", "hint": "Does that make me crazy? Probably"},
    {"artist": "Nickelback", "song": "How You Remind Me", "year": "2001", "hint": "Never made it as a wise man"},
    {"artist": "Sean Paul", "song": "Get Busy", "year": "2002", "hint": "Shake that thing miss Kana Kana"},
    {"artist": "Amy Winehouse", "song": "Rehab", "year": "2006", "hint": "They tried to make me go to rehab, I said no no no"},
    {"artist": "Pitbull", "song": "Hotel Room Service", "year": "2009", "hint": "Forget about your boyfriend and meet me at the hotel room"},
    {"artist": "Flo Rida ft. T-Pain", "song": "Low", "year": "2007", "hint": "Shawty had them apple bottom jeans, boots with the fur"},
    {"artist": "Green Day", "song": "Boulevard of Broken Dreams", "year": "2004", "hint": "I walk a lonely road, the only one that I have ever known"},
    {"artist": "Franz Ferdinand", "song": "Take Me Out", "year": "2004", "hint": "So if you're lonely, you know I'm here waiting for you"},
    {"artist": "The White Stripes", "song": "Seven Nation Army", "year": "2003", "hint": "Iconic bassline chanted in stadiums worldwide"},
    {"artist": "Avril Lavigne", "song": "Sk8er Boi", "year": "2002", "hint": "He was a boy, she was a girl, can I make it any more obvious?"},
    {"artist": "50 Cent", "song": "In Da Club", "year": "2003", "hint": "Go shorty, it's your birthday"},
    {"artist": "Gorillaz", "song": "Feel Good Inc.", "year": "2005", "hint": "Windmill, windmill for the land"},
    # N: 31-45
    {"artist": "Avril Lavigne", "song": "Complicated", "year": "2002", "hint": "Why'd you have to go and make things so complicated?"},
    {"artist": "Evanescence", "song": "Bring Me to Life", "year": "2003", "hint": "Wake me up inside, save me!"},
    {"artist": "Snow Patrol", "song": "Chasing Cars", "year": "2006", "hint": "If I lay here, if I just lay here"},
    {"artist": "Britney Spears", "song": "Toxic", "year": "2003", "hint": "Taste of your lips, I'm on a ride"},
    {"artist": "Kings of Leon", "song": "Sex on Fire", "year": "2008", "hint": "You, your sex is on fire"},
    {"artist": "Alicia Keys", "song": "No One", "year": "2007", "hint": "No one, no one, no one can get in the way of what I'm feeling"},
    {"artist": "Daft Punk", "song": "One More Time", "year": "2000", "hint": "One more time, we're gonna celebrate"},
    {"artist": "Kanye West", "song": "Stronger", "year": "2007", "hint": "Harder, better, faster, stronger"},
    {"artist": "Wheatus", "song": "Teenage Dirtbag", "year": "2000", "hint": "'Cause I'm just a teenage dirtbag baby"},
    {"artist": "Jet", "song": "Are You Gonna Be My Girl", "year": "2003", "hint": "Big black boots, long brown hair"},
    {"artist": "Jason Mraz", "song": "I'm Yours", "year": "2008", "hint": "Well, you done done me and you bet I felt it"},
    {"artist": "P!nk", "song": "Get the Party Started", "year": "2001", "hint": "I'm comin' up, so you better get this party started"},
    {"artist": "Cascada", "song": "Everytime We Touch", "year": "2005", "hint": "'Cause everytime we touch, I get this feeling"},
    {"artist": "Gym Class Heroes", "song": "Cupid's Chokehold", "year": "2005", "hint": "Take a look at my girlfriend, she's the only one I got"},
    {"artist": "Shaggy", "song": "It Wasn't Me", "year": "2000", "hint": "Caught me red-handed creeping with the girl next door"},
    # G: 46-60
    {"artist": "Natasha Bedingfield", "song": "Unwritten", "year": "2004", "hint": "Feel the rain on your skin"},
    {"artist": "Nelly Furtado", "song": "Promiscuous", "year": "2006", "hint": "Promiscuous girl, wherever you are"},
    {"artist": "Scissor Sisters", "song": "I Don't Feel Like Dancin'", "year": "2006", "hint": "When the old piano plays"},
    {"artist": "M.I.A.", "song": "Paper Planes", "year": "2007", "hint": "All I wanna do is *gunshots* and take your money"},
    {"artist": "Mika", "song": "Grace Kelly", "year": "2007", "hint": "I could be brown, I could be blue, I could be violet sky"},
    {"artist": "Foo Fighters", "song": "The Pretender", "year": "2007", "hint": "What if I say I'm not like the others?"},
    {"artist": "Kylie Minogue", "song": "Can't Get You Out of My Head", "year": "2001", "hint": "La la la, la la la la la"},
    {"artist": "MGMT", "song": "Kids", "year": "2007", "hint": "Control yourself, take only what you need from it"},
    {"artist": "Kaiser Chiefs", "song": "Ruby", "year": "2007", "hint": "Ruby, Ruby, Ruby, Ruby!"},
    {"artist": "Plain White T's", "song": "Hey There Delilah", "year": "2006", "hint": "What's it like in New York City?"},
    {"artist": "David Guetta ft. Akon", "song": "Sexy Bitch", "year": "2009", "hint": "Yes I can see her, 'cause every girl in here wanna be her"},
    {"artist": "T-Pain", "song": "Buy U a Drank (Shawty Snappin')", "year": "2007", "hint": "I'ma buy you a drank"},
    {"artist": "Santana ft. Michelle Branch", "song": "The Game of Love", "year": "2002", "hint": "Tell me, just a little bit of love"},
    {"artist": "Nelly ft. Kelly Rowland", "song": "Dilemma", "year": "2002", "hint": "No matter what I do, all I think about is you"},
    {"artist": "Timbaland ft. OneRepublic", "song": "Apologize", "year": "2007", "hint": "It's too late to apologize"},
    # O: 61-75
    {"artist": "The Fray", "song": "How to Save a Life", "year": "2005", "hint": "Where did I go wrong? I lost a friend"},
    {"artist": "Panic! At the Disco", "song": "I Write Sins Not Tragedies", "year": "2005", "hint": "I chime in with a 'Haven't you people ever heard of closing a goddamn door?'"},
    {"artist": "All-American Rejects", "song": "Dirty Little Secret", "year": "2005", "hint": "I'll keep you my dirty little secret"},
    {"artist": "Empire of the Sun", "song": "Walking on a Dream", "year": "2008", "hint": "We are always running for the thrill of it"},
    {"artist": "Feist", "song": "1234", "year": "2007", "hint": "1, 2, 3, 4, tell me that you love me more"},
    {"artist": "The Strokes", "song": "Last Nite", "year": "2001", "hint": "Last night she said, oh baby don't feel so down"},
    {"artist": "Teddybears ft. Mad Cobra", "song": "Cobrastyle", "year": "2004", "hint": "My style is the bomb style"},
    {"artist": "The Darkness", "song": "I Believe in a Thing Called Love", "year": "2003", "hint": "Just listen to the rhythm of my heart"},
    {"artist": "Keane", "song": "Somewhere Only We Know", "year": "2004", "hint": "I walked across an empty land"},
    {"artist": "Train", "song": "Drops of Jupiter", "year": "2001", "hint": "Now that she's back from that soul vacation"},
    {"artist": "Muse", "song": "Supermassive Black Hole", "year": "2006", "hint": "Glaciers melting in the dead of night"},
    {"artist": "The Ting Tings", "song": "That's Not My Name", "year": "2008", "hint": "They call me Stacy, they call me Jane"},
    {"artist": "The Offspring", "song": "You're Gonna Go Far, Kid", "year": "2008", "hint": "Show me how to lie, you're getting better all the time"},
    {"artist": "Duffy", "song": "Mercy", "year": "2008", "hint": "Yeah release me, beg you for mercy"},
    {"artist": "Black Eyed Peas", "song": "Where Is the Love?", "year": "2003", "hint": "People killing, people dying"}
]
sets_data.append(make_music_set(5, "2000s Pop & Party Anthems", "2000s Hits", "music-2000s", "The biggest millennial bangers, indie anthems, and club singalongs of the 2000s.", "fa-headphones", tracks_2000s))

# Mzansi Hits & South African Classics (75 Tracks)
tracks_mzansi = [
    # B: 1-15
    {"artist": "Brenda Fassie", "song": "Vul'indlela", "year": "1997", "hint": "Legendary wedding celebration anthem"},
    {"artist": "Mandoza", "song": "Nkalakatha", "year": "2000", "hint": "The ultimate South African cross-culture anthem"},
    {"artist": "Mango Groove", "song": "Special Star", "year": "1989", "hint": "Pennywhistle magic with Claire Johnston"},
    {"artist": "Johnny Clegg & Savuka", "song": "Scatterlings of Africa", "year": "1987", "hint": "The White Zulu anthem"},
    {"artist": "Master KG ft. Nomcebo", "song": "Jerusalema", "year": "2019", "hint": "Global dance sensation from Limpopo"},
    {"artist": "Mi Casa", "song": "Jika", "year": "2013", "hint": "Baby won't you just dance with me"},
    {"artist": "Kurt Darren", "song": "Kaptein (Span Die Seile)", "year": "2008", "hint": "Die son sak weg oor die horison"},
    {"artist": "Mafikizolo", "song": "Ndihamba Nawe", "year": "2002", "hint": "Kwaito-Afropop royalty"},
    {"artist": "Jeremy Loops", "song": "Down South", "year": "2014", "hint": "Live folk looping grooves"},
    {"artist": "Freshlyground", "song": "Doo Be Doo", "year": "2004", "hint": "All I wanna do is love you all the time"},
    {"artist": "Prime Circle", "song": "She Always Gets What She Wants", "year": "2008", "hint": "SA rock anthems"},
    {"artist": "TKZee", "song": "Shibobo", "year": "1998", "hint": "World Cup 1998 classic with Benni McCarthy"},
    {"artist": "Watershed", "song": "Indigo Girl", "year": "2000", "hint": "Craig Hinds piano classic"},
    {"artist": "DJ Maphorisa & Kabza De Small", "song": "Lorch", "year": "2019", "hint": "Amapiano royalty named after Thembinkosi Lorch"},
    {"artist": "Miriam Makeba", "song": "Pata Pata", "year": "1967", "hint": "Mama Africa's most famous worldwide hit"},
    # I: 16-30
    {"artist": "Clout", "song": "Substitute", "year": "1977", "hint": "All-female SA rock chart topper"},
    {"artist": "Bright Blue", "song": "Weeping", "year": "1987", "hint": "Features the hidden melody of Nkosi Sikelel' iAfrika"},
    {"artist": "Matthew Mole", "song": "Take Yours, I'll Take Mine", "year": "2013", "hint": "Upbeat acoustic folk pop"},
    {"artist": "Sipho 'Hotstix' Mabuse", "song": "Burn Out", "year": "1984", "hint": "Pioneering afro-disco township groove"},
    {"artist": "Lucky Dube", "song": "Remember Me", "year": "1989", "hint": "Reggae legend of South Africa"},
    {"artist": "Hugh Masekela", "song": "Grazing in the Grass", "year": "1968", "hint": "Flugelhorn number 1 on Billboard"},
    {"artist": "Zebra & Giraffe", "song": "The Inside", "year": "2008", "hint": "SA alternative rock favorite"},
    {"artist": "Gangs of Ballet", "song": "Don't Let Me Go", "year": "2013", "hint": "Durban indie rock"},
    {"artist": "Fokofpolisiekar", "song": "Hemel op die Platteland", "year": "2003", "hint": "Kan iemand dalk 'n god bel?"},
    {"artist": "Bok van Blerk", "song": "De La Rey", "year": "2006", "hint": "Sal jy die Boere kom lei?"},
    {"artist": "DJ Cleo", "song": "Facebook", "year": "2010", "hint": "Will you be my Facebook friend?"},
    {"artist": "Just Jinjer", "song": "What He Means", "year": "1998", "hint": "Ard Matthews acoustic rock masterwork"},
    {"artist": "Die Heuwels Fantasties", "song": "Leja", "year": "2009", "hint": "Electro-pop Afrikaans revolution"},
    {"artist": "Francois van Coke & Karen Zoid", "song": "Toe Vind Ek Jou", "year": "2015", "hint": "Rock ballad duet of the decade"},
    {"artist": "Rabbitt (Trevor Rabin)", "song": "Charlie", "year": "1976", "hint": "70s SA teen rock mania"},
    # N: 31-45
    {"artist": "Johnny Clegg & Juluka", "song": "Impi", "year": "1981", "hint": "Impi! Wo 'nans' impi iyeza"},
    {"artist": "Mango Groove", "song": "Dance Some More", "year": "1989", "hint": "Kwela brass horns and joyful vocals"},
    {"artist": "Brenda Fassie", "song": "Weekend Special", "year": "1983", "hint": "Township pop breakthrough"},
    {"artist": "Mandoza", "song": "Godoba", "year": "2001", "hint": "Signature rough bass kwaito"},
    {"artist": "Mafikizolo ft. Uhuru", "song": "Khona", "year": "2013", "hint": "House beat that shook all of Africa"},
    {"artist": "Lira", "song": "Feel Good", "year": "2006", "hint": "Smooth Afro-soul anthem"},
    {"artist": "Kurt Darren", "song": "Loslappie", "year": "2006", "hint": "Sokkie dancefloor essential"},
    {"artist": "Springbok Nude Girls", "song": "Bubblegum On My Boots", "year": "1997", "hint": "Arno Carstens rock powerhouse"},
    {"artist": "Farafina & Ladysmith Black Mambazo", "song": "Homeless", "year": "1986", "hint": "Graceland harmonies with Paul Simon"},
    {"artist": "Dr Victor & The Rasta Rebels", "song": "Give Me Hope Jo'anna", "year": "1991", "hint": "Reggae party staple at every braai"},
    {"artist": "Kahn Morbee & Karen Zoid", "song": "We Could Be Divine", "year": "2015", "hint": "The Voice SA coaches duet"},
    {"artist": "Shortstraw", "song": "Couch Potato", "year": "2013", "hint": "Joburg indie surf rock"},
    {"artist": "aKing", "song": "Safe as Houses", "year": "2008", "hint": "Bellville melodic rock"},
    {"artist": "Karen Zoid", "song": "Afrikaners Is Plesierig", "year": "2001", "hint": "Hulle hou van partytjies"},
    {"artist": "Spoegwolf", "song": "Lenie Blou", "year": "2019", "hint": "Paarl alternative folk rock"},
    # G: 46-60
    {"artist": "e-Void", "song": "Taximan", "year": "1983", "hint": "Jive jive taxi jive"},
    {"artist": "PJ Powers & Hotline", "song": "Jabulani", "year": "1985", "hint": "Township pop cross-over"},
    {"artist": "Cinema", "song": "Strangers Again", "year": "1987", "hint": "SA 80s synth ballad"},
    {"artist": "Goldfish", "song": "Fort Knox", "year": "2008", "hint": "Cape Town live jazz electro"},
    {"artist": "Goldfish", "song": "Hold Tight", "year": "2008", "hint": "Saxophone driven dance"},
    {"artist": "GoodLuck", "song": "Taking It Easy", "year": "2011", "hint": "Electro-swing pop banger"},
    {"artist": "Locnville", "song": "Sun In My Pocket", "year": "2010", "hint": "Chaplin twin brothers electro hit"},
    {"artist": "Die Antwoord", "song": "Enter the Ninja", "year": "2010", "hint": "Zef rap rave viral phenomenon"},
    {"artist": "Jack Parow ft. Francois van Coke", "song": "Dans Dans Dans", "year": "2009", "hint": "Met sy lang pet en kwaito-rap"},
    {"artist": "Koos Kombuis", "song": "Lisa se Klavier", "year": "1994", "hint": "Die lug is blou, die son is warm"},
    {"artist": "The Parlotones", "song": "Colorful", "year": "2005", "hint": "Kahn Morbee signature vocals"},
    {"artist": "The Parlotones", "song": "Push Me to the Floor", "year": "2009", "hint": "Symphony of heartbeats"},
    {"artist": "Prime Circle", "song": "Hello", "year": "2002", "hint": "Ross Learmonth soaring rock vocals"},
    {"artist": "Taxi Violence", "song": "Unholy", "year": "2006", "hint": "Blues rock banger"},
    {"artist": "CrashCarBurn", "song": "Broken Bones", "year": "2007", "hint": "Pop punk power"},
    # O: 61-75
    {"artist": "Kwesta ft. Cassper Nyovest", "song": "Ngud'", "year": "2016", "hint": "Township hip hop masterpiece"},
    {"artist": "AKA", "song": "Congratulate", "year": "2014", "hint": "Supa Mega celebration anthem"},
    {"artist": "Nasty C", "song": "Hell Naw", "year": "2016", "hint": "Durban rap phenom"},
    {"artist": "Focalistic ft. Vigro Deep", "song": "Ke Star", "year": "2020", "hint": "Ase trap ke pina tsa ko kasi"},
    {"artist": "Sun-El Musician ft. Simmy", "song": "Sonini", "year": "2018", "hint": "Afro-house spiritual magic"},
    {"artist": "Black Coffee ft. Bucie", "song": "Superman", "year": "2010", "hint": "Grammy-winning DJ's early classic"},
    {"artist": "DJ Zinhle ft. Tamara Dey", "song": "My Name Is", "year": "2012", "hint": "SA dancefloor staple"},
    {"artist": "MonArk", "song": "Build It Up", "year": "2014", "hint": "High falsetto pop"},
    {"artist": "Theuns Jordaan", "song": "Soos Bloed", "year": "2000", "hint": "Deep acoustic gravel vocals"},
    {"artist": "Karlien van Jaarsveld", "song": "Hande", "year": "2013", "hint": "Afrikaans pop favorite"},
    {"artist": "Snotkop", "song": "Cool Soos Koos Kombuis", "year": "2014", "hint": "Fast party party beats"},
    {"artist": "Dozi", "song": "Ou Ryperd", "year": "2000", "hint": "Ons ry deur die nag"},
    {"artist": "Gerrie Pretorius", "song": "Annies Song", "year": "2004", "hint": "High tenor classic"},
    {"artist": "Radio Kalahari Orkes", "song": "Kaptein", "year": "2007", "hint": "Boere-folk with Ian Roberts"},
    {"artist": "David Kramer", "song": "Hak Hom Blokkies", "year": "1981", "hint": "Red veldskoene rugby legend"}
]
sets_data.append(make_music_set(6, "Mzansi Hits & South African Braai Grooves", "Mzansi Hits", "music-sa", "From Brenda Fassie and Mandoza to Mango Groove, Kurt Darren, and Amapiano bangers.", "fa-fire", tracks_mzansi))

# Rock Legends & Stadium Bangers (75 Tracks)
tracks_rock = [
    # B: 1-15
    {"artist": "AC/DC", "song": "Thunderstruck", "year": "1990", "hint": "Rode down the highway, broke the limit"},
    {"artist": "Led Zeppelin", "song": "Whole Lotta Love", "year": "1969", "hint": "Way down inside, honey you need it"},
    {"artist": "Metallica", "song": "Enter Sandman", "year": "1991", "hint": "Say your prayers little one, don't forget my son"},
    {"artist": "Queen", "song": "We Will Rock You", "year": "1977", "hint": "Buddy, you're a boy, make a big noise"},
    {"artist": "The Rolling Stones", "song": "Paint It Black", "year": "1966", "hint": "I see a red door and I want it painted black"},
    {"artist": "Foo Fighters", "song": "Everlong", "year": "1997", "hint": "Hello, I've waited here for you"},
    {"artist": "Deep Purple", "song": "Smoke on the Water", "year": "1972", "hint": "Fire in the sky!"},
    {"artist": "Iron Maiden", "song": "The Number of the Beast", "year": "1982", "hint": "Six six six, the number of the beast"},
    {"artist": "Black Sabbath", "song": "Paranoid", "year": "1970", "hint": "Finished with my woman 'cause she couldn't help me with my mind"},
    {"artist": "KISS", "song": "Rock and Roll All Nite", "year": "1975", "hint": "And party every day!"},
    {"artist": "Aerosmith", "song": "Dream On", "year": "1973", "hint": "Sing with me, sing for the year"},
    {"artist": "Boston", "song": "More Than a Feeling", "year": "1976", "hint": "I looked out this morning and the sun was gone"},
    {"artist": "Lynyrd Skynyrd", "song": "Sweet Home Alabama", "year": "1974", "hint": "Where the skies are so blue"},
    {"artist": "Ozzy Osbourne", "song": "Crazy Train", "year": "1980", "hint": "All aboard! Ha ha ha ha ha"},
    {"artist": "Alice Cooper", "song": "Poison", "year": "1989", "hint": "Your lips are venomous poison"},
    # I: 16-30
    {"artist": "Thin Lizzy", "song": "The Boys Are Back in Town", "year": "1976", "hint": "Guess who just got back today?"},
    {"artist": "The Who", "song": "Baba O'Riley", "year": "1971", "hint": "Teenage wasteland!"},
    {"artist": "Pearl Jam", "song": "Alive", "year": "1991", "hint": "Son, she said, have I got a little story for you"},
    {"artist": "Soundgarden", "song": "Black Hole Sun", "year": "1994", "hint": "Won't you come and wash away the rain?"},
    {"artist": "Rage Against The Machine", "song": "Killing in the Name", "year": "1992", "hint": "Now you do what they told ya"},
    {"artist": "Red Hot Chili Peppers", "song": "Californication", "year": "1999", "hint": "Psychic spies from China try to steal your mind's elation"},
    {"artist": "Muse", "song": "Knights of Cydonia", "year": "2006", "hint": "No one's gonna take me alive!"},
    {"artist": "Royal Blood", "song": "Figure It Out", "year": "2014", "hint": "Bass guitar fuzz powerhouse"},
    {"artist": "Wolfmother", "song": "Joker and the Thief", "year": "2005", "hint": "I said the joker is a wanted man"},
    {"artist": "The White Stripes", "song": "Fell in Love with a Girl", "year": "2001", "hint": "Red hair with a curl"},
    {"artist": "The Black Keys", "song": "Lonely Boy", "year": "2011", "hint": "Well I'm so easy to please"},
    {"artist": "Queens of the Stone Age", "song": "No One Knows", "year": "2002", "hint": "We get these pills to swallow"},
    {"artist": "Creedence Clearwater Revival", "song": "Fortunate Son", "year": "1969", "hint": "It ain't me, it ain't me, I ain't no senator's son"},
    {"artist": "Judas Priest", "song": "Breaking the Law", "year": "1980", "hint": "Breaking the law, breaking the law!"},
    {"artist": "Motorhead", "song": "Ace of Spades", "year": "1980", "hint": "The dead man's hand again"},
    # N: 31-45
    {"artist": "Van Halen", "song": "Panama", "year": "1984", "hint": "Jump back, what's that sound?"},
    {"artist": "Bon Jovi", "song": "You Give Love a Bad Name", "year": "1986", "hint": "Shot through the heart, and you're to blame"},
    {"artist": "Guns N' Roses", "song": "Paradise City", "year": "1987", "hint": "Where the grass is green and the girls are pretty"},
    {"artist": "Def Leppard", "song": "Photograph", "year": "1983", "hint": "I want more than a picture"},
    {"artist": "AC/DC", "song": "Highway to Hell", "year": "1979", "hint": "No stop signs, speed limit, nobody's gonna slow me down"},
    {"artist": "Scorpions", "song": "Rock You Like a Hurricane", "year": "1984", "hint": "Here I am!"},
    {"artist": "Led Zeppelin", "song": "Kashmir", "year": "1975", "hint": "Oh let the sun beat down upon my face"},
    {"artist": "Queen", "song": "Bohemian Rhapsody", "year": "1975", "hint": "Is this the real life? Is this just fantasy?"},
    {"artist": "The Jimi Hendrix Experience", "song": "Purple Haze", "year": "1967", "hint": "'Scuse me while I kiss the sky"},
    {"artist": "The Doors", "song": "Light My Fire", "year": "1967", "hint": "Come on baby, light my fire"},
    {"artist": "Cream", "song": "Sunshine of Your Love", "year": "1967", "hint": "It's getting near dawn, when lights close their tired eyes"},
    {"artist": "ZZ Top", "song": "Sharp Dressed Man", "year": "1983", "hint": "Top coat, top hat, black shades, white spats"},
    {"artist": "Bad Company", "song": "Feel Like Makin' Love", "year": "1975", "hint": "Baby, when I think about you"},
    {"artist": "Free", "song": "All Right Now", "year": "1970", "hint": "There she stood in the street"},
    {"artist": "Survivor", "song": "Burning Heart", "year": "1985", "hint": "Rocky IV soundtrack banger"},
    # G: 46-60
    {"artist": "Nickelback", "song": "Rockstar", "year": "2005", "hint": "'Cause we all just wanna be big rockstars"},
    {"artist": "3 Doors Down", "song": "Kryptonite", "year": "2000", "hint": "If I go crazy, will you still call me Superman?"},
    {"artist": "Audioslave", "song": "Like a Stone", "year": "2002", "hint": "Chris Cornell powerhouse vocals"},
    {"artist": "Incubus", "song": "Drive", "year": "1999", "hint": "Whatever tomorrow brings, I'll be there"},
    {"artist": "The Cult", "song": "She Sells Sanctuary", "year": "1985", "hint": "Goth rock stadium roar"},
    {"artist": "Billy Idol", "song": "Rebel Yell", "year": "1983", "hint": "More, more, more!"},
    {"artist": "Iggy Pop", "song": "The Passenger", "year": "1977", "hint": "La la la la la la la la"},
    {"artist": "The Clash", "song": "London Calling", "year": "1979", "hint": "To the faraway towns"},
    {"artist": "Sex Pistols", "song": "Anarchy in the U.K.", "year": "1976", "hint": "I am an antichrist, I am an anarchist"},
    {"artist": "The Ramones", "song": "Blitzkrieg Bop", "year": "1976", "hint": "Hey! Ho! Let's go!"},
    {"artist": "Mötley Crüe", "song": "Kickstart My Heart", "year": "1989", "hint": "When I get high I get high on speed"},
    {"artist": "Quiet Riot", "song": "Cum On Feel the Noize", "year": "1983", "hint": "Girls, rock your boys"},
    {"artist": "Twisted Sister", "song": "I Wanna Rock", "year": "1984", "hint": "ROCK!"},
    {"artist": "Dio", "song": "Holy Diver", "year": "1983", "hint": "You've been down too long in the midnight sea"},
    {"artist": "Whitesnake", "song": "Is This Love", "year": "1987", "hint": "That I'm feeling, is this the love that I've been searching for?"},
    # O: 61-75
    {"artist": "U2", "song": "Sunday Bloody Sunday", "year": "1983", "hint": "How long, how long must we sing this song?"},
    {"artist": "Kings of Leon", "song": "Use Somebody", "year": "2008", "hint": "You know that I could use somebody"},
    {"artist": "The Black Crowes", "song": "Hard to Handle", "year": "1990", "hint": "Baby here I am, I'm a man on the scene"},
    {"artist": "Lenny Kravitz", "song": "Are You Gonna Go My Way", "year": "1993", "hint": "Fuzz guitar riff masterclass"},
    {"artist": "Status Quo", "song": "Rockin' All Over the World", "year": "1977", "hint": "And I like it, I like it, I li-li-like it"},
    {"artist": "Sweet", "song": "Ballroom Blitz", "year": "1973", "hint": "And the man at the back said 'Everyone attack'"},
    {"artist": "Deep Purple", "song": "Highway Star", "year": "1972", "hint": "Nobody gonna take my car, I'm gonna race it to the ground"},
    {"artist": "Heart", "song": "Barracuda", "year": "1977", "hint": "Ooooh, barracuda!"},
    {"artist": "Pat Benatar", "song": "Hit Me with Your Best Shot", "year": "1980", "hint": "Fire away!"},
    {"artist": "Joan Jett", "song": "Bad Reputation", "year": "1981", "hint": "I don't give a damn 'bout my bad reputation"},
    {"artist": "Gary Moore", "song": "Still Got the Blues", "year": "1990", "hint": "So long ago, but it's still with me today"},
    {"artist": "Slash ft. Myles Kennedy", "song": "Anastasia", "year": "2012", "hint": "Classical guitar intro shred"},
    {"artist": "Rival Sons", "song": "Do Your Worst", "year": "2018", "hint": "Modern raw vintage blues rock"},
    {"artist": "Greta Van Fleet", "song": "Highway Tune", "year": "2017", "hint": "Soaring Zeppelin-esque rock revival"},
    {"artist": "The Darkness", "song": "Growing On Me", "year": "2003", "hint": "Can't get you out of my hair"}
]
sets_data.append(make_music_set(7, "Rock Legends & Stadium Bangers", "Classic Rock", "music-rock", "Maximum decibels! Headbanging guitar riffs, solos, and anthems that shook arenas.", "fa-guitar", tracks_rock))

# Blockbuster Movies & TV Themes (75 Tracks)
tracks_movies = [
    # B: 1-15
    {"artist": "Kenny Loggins", "song": "Danger Zone", "year": "1986", "hint": "Top Gun theme song"},
    {"artist": "John Williams", "song": "Star Wars (Imperial March)", "year": "1980", "hint": "Darth Vader's epic march"},
    {"artist": "John Travolta & Olivia Newton-John", "song": "You're the One That I Want", "year": "1978", "hint": "Grease musical climax"},
    {"artist": "Elton John", "song": "Circle of Life", "year": "1994", "hint": "The Lion King opening anthem"},
    {"artist": "Ray Parker Jr.", "song": "Ghostbusters", "year": "1984", "hint": "Who you gonna call? Ghostbusters!"},
    {"artist": "The Rembrandts", "song": "I'll Be There for You", "year": "1994", "hint": "Friends TV theme"},
    {"artist": "Celine Dion", "song": "My Heart Will Go On", "year": "1997", "hint": "Titanic love theme"},
    {"artist": "Bill Medley & Jennifer Warnes", "song": "(I've Had) The Time of My Life", "year": "1987", "hint": "Dirty Dancing lift climax"},
    {"artist": "Survivor", "song": "Eye of the Tiger", "year": "1982", "hint": "Rocky III boxing training montage"},
    {"artist": "Will Smith", "song": "Men in Black", "year": "1997", "hint": "Here come the Men in Black, galaxy defenders"},
    {"artist": "Dick Dale", "song": "Misirlou", "year": "1994", "hint": "Pulp Fiction surf guitar opening"},
    {"artist": "Will Smith", "song": "The Fresh Prince of Bel-Air", "year": "1990", "hint": "Now this is a story all about how my life got flipped turned upside down"},
    {"artist": "Ramin Djawadi", "song": "Game of Thrones Theme", "year": "2011", "hint": "Epic cello intro to Westeros"},
    {"artist": "John Williams", "song": "Jurassic Park Theme", "year": "1993", "hint": "Majestic dinosaur reveal theme"},
    {"artist": "Lalo Schifrin", "song": "Mission: Impossible Theme", "year": "1966", "hint": "5/4 time signature spy anthem"},
    # I: 16-30
    {"artist": "Huey Lewis and the News", "song": "The Power of Love", "year": "1985", "hint": "Back to the Future Marty McFly skateboard intro"},
    {"artist": "Bee Gees", "song": "Stayin' Alive", "year": "1977", "hint": "Saturday Night Fever Tony Manero strut"},
    {"artist": "Monty Norman", "song": "James Bond 007 Theme", "year": "1962", "hint": "Shaken, not stirred"},
    {"artist": "Harold Faltermeyer", "song": "Axel F", "year": "1984", "hint": "Beverly Hills Cop synth classic"},
    {"artist": "The Jimi Jamison Band", "song": "I'm Always Here", "year": "1989", "hint": "Baywatch slow-motion beach run"},
    {"artist": "Henry Mancini", "song": "The Pink Panther Theme", "year": "1963", "hint": "Sneaky saxophone stealth"},
    {"artist": "Smash Mouth", "song": "All Star", "year": "2001", "hint": "Shrek opening scene"},
    {"artist": "Redbone", "song": "Come and Get Your Love", "year": "2014", "hint": "Guardians of the Galaxy intro dance"},
    {"artist": "Wiz Khalifa ft. Charlie Puth", "song": "See You Again", "year": "2015", "hint": "Furious 7 Paul Walker farewell"},
    {"artist": "Hugh Jackman & Cast", "song": "The Greatest Show", "year": "2017", "hint": "The Greatest Showman spectacle"},
    {"artist": "Simple Minds", "song": "Don't You (Forget About Me)", "year": "1985", "hint": "The Breakfast Club fist pump"},
    {"artist": "Berlin", "song": "Take My Breath Away", "year": "1986", "hint": "Top Gun romance love theme"},
    {"artist": "Seal", "song": "Kiss from a Rose", "year": "1995", "hint": "Batman Forever soundtrack smash"},
    {"artist": "Whitney Houston", "song": "I Will Always Love You", "year": "1992", "hint": "The Bodyguard record-breaking ballad"},
    {"artist": "Michael Jackson", "song": "Thriller", "year": "1982", "hint": "Vincent Price laughing voiceover horror movie video"},
    # N: 31-45
    {"artist": "Adele", "song": "Skyfall", "year": "2012", "hint": "Oscar-winning 007 Bond anthem"},
    {"artist": "Pharrell Williams", "song": "Happy", "year": "2013", "hint": "Despicable Me 2 cheerful stomp"},
    {"artist": "Irene Cara", "song": "Fame", "year": "1980", "hint": "Remember my name, Fame!"},
    {"artist": "Irene Cara", "song": "Flashdance... What a Feeling", "year": "1983", "hint": "Take your passion and make it happen"},
    {"artist": "Simon & Garfunkel", "song": "Mrs. Robinson", "year": "1968", "hint": "The Graduate classic"},
    {"artist": "Steppenwolf", "song": "Born to Be Wild", "year": "1968", "hint": "Easy Rider biker anthem"},
    {"artist": "Limp Bizkit", "song": "Take a Look Around", "year": "2000", "hint": "Mission: Impossible 2 rap-rock"},
    {"artist": "Coolio ft. L.V.", "song": "Gangsta's Paradise", "year": "1995", "hint": "Dangerous Minds Michelle Pfeiffer classroom"},
    {"artist": "Roy Orbison", "song": "Oh, Pretty Woman", "year": "1990", "hint": "Pretty Woman Julia Roberts shopping montage"},
    {"artist": "Prince", "song": "Batdance", "year": "1989", "hint": "Batman 1989 soundtrack"},
    {"artist": "John Williams", "song": "Raiders of the Lost Ark March", "year": "1981", "hint": "Indiana Jones whip and fedora"},
    {"artist": "Danny Elfman", "song": "The Simpsons Theme", "year": "1989", "hint": "Couch gag intro"},
    {"artist": "Mike Post", "song": "The A-Team Theme", "year": "1983", "hint": "If you have a problem, if no one else can help"},
    {"artist": "Stu Phillips", "song": "Knight Rider Theme", "year": "1982", "hint": "KITT the talking Pontiac Trans Am"},
    {"artist": "Brad Fiedel", "song": "The Terminator Theme", "year": "1984", "hint": "Clang clang clang-clang-clang metallic synth"},
    # G: 46-60
    {"artist": "Alan Silvestri", "song": "The Avengers Theme", "year": "2012", "hint": "Marvel cinematic brass crescendo"},
    {"artist": "Hans Zimmer", "song": "Pirates of the Caribbean (He's a Pirate)", "year": "2003", "hint": "Captain Jack Sparrow pirate swashbuckler"},
    {"artist": "Kavinsky", "song": "Nightcall", "year": "2011", "hint": "Drive Ryan Gosling retro synthwave"},
    {"artist": "Lorde", "song": "Yellow Flicker Beat", "year": "2014", "hint": "The Hunger Games: Mockingjay"},
    {"artist": "Justin Timberlake", "song": "Can't Stop the Feeling!", "year": "2016", "hint": "Trolls animated hit"},
    {"artist": "Idina Menzel", "song": "Let It Go", "year": "2013", "hint": "Disney's Frozen ice palace anthem"},
    {"artist": "Randy Newman", "song": "You've Got a Friend in Me", "year": "1995", "hint": "Toy Story Woody and Buzz friendship"},
    {"artist": "The B-52's", "song": "Meet the Flintstones", "year": "1994", "hint": "Yabba dabba doo modern stone-age family"},
    {"artist": "Gary Jules", "song": "Mad World", "year": "2001", "hint": "Donnie Darko haunting piano cover"},
    {"artist": "Chuck Berry", "song": "You Never Can Tell", "year": "1994", "hint": "Pulp Fiction twist dance competition at Jack Rabbit Slim's"},
    {"artist": "Los Lobos & Antonio Banderas", "song": "Cancion Del Mariachi", "year": "1995", "hint": "Desperado guitar bar entrance"},
    {"artist": "Nancy Sinatra", "song": "Bang Bang (My Baby Shot Me Down)", "year": "2003", "hint": "Kill Bill Vol. 1 opening title"},
    {"artist": "Bernard Herrmann", "song": "Psycho (The Murder)", "year": "1960", "hint": "Terrifying screeching shower scene violins"},
    {"artist": "Ennio Morricone", "song": "The Good, the Bad and the Ugly", "year": "1966", "hint": "Coyote whistle spaghetti western duel"},
    {"artist": "Ennio Morricone", "song": "Gabriel's Oboe", "year": "1986", "hint": "The Mission emotional woodwind"},
    # O: 61-75
    {"artist": "Joe Cocker & Jennifer Warnes", "song": "Up Where We Belong", "year": "1982", "hint": "An Officer and a Gentleman"},
    {"artist": "Bruce Springsteen", "song": "Streets of Philadelphia", "year": "1993", "hint": "Philadelphia Tom Hanks Oscar winner"},
    {"artist": "Jon Bon Jovi", "song": "Blaze of Glory", "year": "1990", "hint": "Young Guns II western ballad"},
    {"artist": "Bryan Adams", "song": "(Everything I Do) I Do It for You", "year": "1991", "hint": "Robin Hood: Prince of Thieves"},
    {"artist": "Tina Turner", "song": "We Don't Need Another Hero", "year": "1985", "hint": "Mad Max Beyond Thunderdome"},
    {"artist": "Duran Duran", "song": "A View to a Kill", "year": "1985", "hint": "007 James Bond Roger Moore title track"},
    {"artist": "Paul McCartney & Wings", "song": "Live and Let Die", "year": "1973", "hint": "007 James Bond orchestra blast"},
    {"artist": "Shirley Bassey", "song": "Goldfinger", "year": "1964", "hint": "He's the man, the man with the Midas touch"},
    {"artist": "Billie Eilish", "song": "No Time to Die", "year": "2020", "hint": "Daniel Craig's final 007 Bond ballad"},
    {"artist": "Glen Hansard & Marketa Irglova", "song": "Falling Slowly", "year": "2007", "hint": "Once indie movie musical Oscar winner"},
    {"artist": "Lady Gaga & Bradley Cooper", "song": "Shallow", "year": "2018", "hint": "A Star Is Born power ballad duet"},
    {"artist": "Keala Settle", "song": "This Is Me", "year": "2017", "hint": "The Greatest Showman bearded lady anthem"},
    {"artist": "Aerosmith", "song": "I Don't Want to Miss a Thing", "year": "1998", "hint": "Armageddon asteroid drill romance"},
    {"artist": "Bette Midler", "song": "Wind Beneath My Wings", "year": "1988", "hint": "Beaches emotional tearjerker"},
    {"artist": "Peabo Bryson & Regina Belle", "song": "A Whole New World", "year": "1992", "hint": "Disney's Aladdin magic carpet ride"}
]
sets_data.append(make_music_set(8, "Blockbuster Movies & TV Theme Songs", "Soundtracks", "music-movies", "Legendary cinema soundtracks, TV themes, and Oscar-winning anthems.", "fa-film", tracks_movies))

# Pub Quiz Trivia Bingo (75 Trivia Clues & Answers)
trivia_items = [
    # B: 1-15
    {"ans": "Eiffel Tower", "q": "Which 330m iron landmark in Paris opened for the 1889 World's Fair?"},
    {"ans": "Pacific Ocean", "q": "What is the largest and deepest ocean on Earth?"},
    {"ans": "Mars", "q": "Which celestial body is famously known as the Red Planet?"},
    {"ans": "Leonardo da Vinci", "q": "Which Renaissance master painted the Mona Lisa and The Last Supper?"},
    {"ans": "Springboks", "q": "What is South Africa's four-time World Cup winning national rugby team called?"},
    {"ans": "William Shakespeare", "q": "Who wrote Hamlet, Romeo and Juliet, and Macbeth?"},
    {"ans": "Tokyo", "q": "What is the capital city of Japan, formerly named Edo?"},
    {"ans": "Oxygen", "q": "Which chemical element has atomic number 8 and is vital for human respiration?"},
    {"ans": "Nile", "q": "Which African river is traditionally considered the longest in the world?"},
    {"ans": "Mercury", "q": "Which planet in our solar system is closest to the Sun?"},
    {"ans": "Gold", "q": "Which precious metal has the chemical symbol Au?"},
    {"ans": "Sahara", "q": "What is the largest hot desert on Earth, covering North Africa?"},
    {"ans": "Table Mountain", "q": "Which flat-topped landmark overlooks Cape Town, South Africa?"},
    {"ans": "Alexander Fleming", "q": "Which Scottish scientist discovered penicillin in 1928?"},
    {"ans": "Blue Whale", "q": "What is the largest animal ever known to have lived on Earth?"},
    # I: 16-30
    {"ans": "Vatican City", "q": "What is the smallest independent state in the world by area and population?"},
    {"ans": "Kruger National Park", "q": "Which world-famous wildlife reserve in Mpumalanga and Limpopo spans 2 million hectares?"},
    {"ans": "Neil Armstrong", "q": "Who was the first person to walk on the Moon in July 1969?"},
    {"ans": "Diamond", "q": "What is the hardest naturally occurring mineral on Mohs hardness scale?"},
    {"ans": "Cheetah", "q": "What is the fastest land animal, capable of sprinting up to 120 km/h?"},
    {"ans": "Canberra", "q": "What is the federal capital city of Australia?"},
    {"ans": "Nelson Mandela", "q": "Who was inaugurated as South Africa's first democratically elected president in 1994?"},
    {"ans": "Beethoven", "q": "Which German composer composed Symphony No. 9 while completely deaf?"},
    {"ans": "Mount Everest", "q": "What is Earth's highest mountain above sea level at 8,848 meters?"},
    {"ans": "Skin", "q": "What is the largest organ of the human body?"},
    {"ans": "Amazon", "q": "Which South American river discharges the greatest volume of water on Earth?"},
    {"ans": "Albert Einstein", "q": "Which physicist formulated the Theory of General Relativity and E=mc²?"},
    {"ans": "Rome", "q": "Which ancient Italian city is nicknamed 'The Eternal City'?"},
    {"ans": "Jupiter", "q": "Which planet is the largest in our solar system?"},
    {"ans": "Ostrich", "q": "What is the world's largest flightless bird, native to Africa?"},
    # N: 31-45
    {"ans": "Great Barrier Reef", "q": "What is the world's largest coral reef system, located off Queensland, Australia?"},
    {"ans": "Protea", "q": "What is South Africa's national flower (the King Protea)?"},
    {"ans": "Isaac Newton", "q": "Which English scientist described the laws of motion and universal gravitation?"},
    {"ans": "Atlantic Ocean", "q": "Which ocean separates the Americas from Europe and Africa?"},
    {"ans": "Biltong", "q": "What beloved South African cured, dried meat snack was created by indigenous people and Voortrekkers?"},
    {"ans": "Venus", "q": "Which planet is known as Earth's twin and the Morning Star?"},
    {"ans": "Mozart", "q": "Which Austrian child prodigy composed The Magic Flute and Eine kleine Nachtmusik?"},
    {"ans": "Ottawa", "q": "What is the capital city of Canada?"},
    {"ans": "Silver", "q": "Which chemical element has the symbol Ag?"},
    {"ans": "Braai", "q": "What is the traditional South African social barbecue called, celebrated on Heritage Day?"},
    {"ans": "K2", "q": "What is the second-highest mountain on Earth, located on the China-Pakistan border?"},
    {"ans": "Charles Darwin", "q": "Which naturalist published 'On the Origin of Species' in 1859?"},
    {"ans": "Grand Canyon", "q": "Which steep-sided gorge carved by the Colorado River is in Arizona, USA?"},
    {"ans": "Rooibos", "q": "Which herbal red bush tea is indigenous to the Cederberg region of South Africa?"},
    {"ans": "Antarctica", "q": "Which frozen continent contains the geographic South Pole?"},
    # G: 46-60
    {"ans": "Vincent van Gogh", "q": "Which post-impressionist master painted 'The Starry Night' and 'Sunflowers'?"},
    {"ans": "Springbok", "q": "What is South Africa's national animal, known for pronking?"},
    {"ans": "Saturn", "q": "Which gas giant is famous for its prominent, spectacular ring system?"},
    {"ans": "Colosseum", "q": "Which ancient oval amphitheatre in the centre of Rome held gladiatorial contests?"},
    {"ans": "Alexander Graham Bell", "q": "Who was awarded the first US patent for the telephone in 1876?"},
    {"ans": "Chameleon", "q": "Which reptile is famous for its independently mobile eyes and colour-changing skin?"},
    {"ans": "Lake Victoria", "q": "What is Africa's largest tropical lake by surface area?"},
    {"ans": "Pretoria", "q": "Which city is the administrative capital of South Africa, famous for its Jacaranda trees?"},
    {"ans": "Iron", "q": "Which metal has the symbol Fe and forms rust when oxidized?"},
    {"ans": "Giraffe", "q": "What is the tallest living terrestrial animal on Earth?"},
    {"ans": "Machu Picchu", "q": "Which 15th-century Inca citadel sits on a mountain ridge in Peru?"},
    {"ans": "Cervantes", "q": "Who wrote the Spanish masterpiece 'Don Quixote'?"},
    {"ans": "Madrid", "q": "What is the capital and largest city of Spain?"},
    {"ans": "Copper", "q": "Which reddish metal with symbol Cu has been used by humans for over 10,000 years?"},
    {"ans": "Platypus", "q": "Which semi-aquatic Australian mammal lays eggs and has a duck-like bill?"},
    # O: 61-75
    {"ans": "Marie Curie", "q": "Who was the first woman to win a Nobel Prize and the only person to win in two scientific fields?"},
    {"ans": "Blue Crane", "q": "What is South Africa's national bird, indigenous to southern Africa?"},
    {"ans": "Taj Mahal", "q": "Which ivory-white marble mausoleum on the Yamuna river was commissioned by Shah Jahan?"},
    {"ans": "Thomas Edison", "q": "Who patented the phonograph, motion picture camera, and practical incandescent light bulb?"},
    {"ans": "Galileo Galilei", "q": "Which Italian astronomer discovered four moons of Jupiter in 1610?"},
    {"ans": "Kilimanjaro", "q": "What is the highest mountain in Africa and the highest single free-standing mountain in the world?"},
    {"ans": "Bloemfontein", "q": "Which city serves as the judicial capital of South Africa, also known as the City of Roses?"},
    {"ans": "Potassium", "q": "Which mineral found in bananas has the chemical symbol K?"},
    {"ans": "Penguin", "q": "Which group of aquatic flightless birds includes the African Penguin at Boulders Beach?"},
    {"ans": "Great Wall of China", "q": "Which ancient fortification spans thousands of kilometres across northern China?"},
    {"ans": "Pablo Picasso", "q": "Which Spanish artist co-founded the Cubist movement and painted 'Guernica'?"},
    {"ans": "Wellington", "q": "What is the southernmost capital city in the world, located in New Zealand?"},
    {"ans": "Helium", "q": "Which noble gas is the second lightest and second most abundant element in the universe?"},
    {"ans": "Real Madrid", "q": "Which football club has won a record 15 UEFA Champions League titles?"},
    {"ans": "Stellenbosch", "q": "Which historic town in the Western Cape is world-renowned for its oak-lined streets and vineyards?"}
]

items_trivia = []
for idx, t in enumerate(trivia_items):
    num = idx + 1
    col = cols_75[idx]
    items_trivia.append({
        "id": num,
        "col": col,
        "call": f"{col}-{num}",
        "title": t["ans"],
        "subtitle": t["q"],
        "rhyme": f"{t['ans']}: {t['q']}",
        "hint": t["q"]
    })

sets_data.append({
    "id": 9,
    "name": "Pub Quiz Trivia Bingo",
    "badge": "Trivia",
    "theme": "trivia",
    "type": "trivia-75",
    "totalItems": 75,
    "description": "General knowledge, bar trivia clues, geography, and fun pop facts on a bingo card.",
    "icon": "fa-brain",
    "cardSize": 5,
    "hasFreeSpace": True,
    "items": items_trivia
})

# Golden 70s Disco Fever & Motown (75 Tracks)
tracks_70s = [
    # B: 1-15
    {"artist": "ABBA", "song": "Dancing Queen", "year": "1976", "hint": "Young and sweet, only seventeen"},
    {"artist": "Bee Gees", "song": "Stayin' Alive", "year": "1977", "hint": "Whether you're a brother or whether you're a mother"},
    {"artist": "Earth, Wind & Fire", "song": "September", "year": "1978", "hint": "Do you remember the 21st night of September?"},
    {"artist": "Gloria Gaynor", "song": "I Will Survive", "year": "1978", "hint": "At first I was afraid, I was petrified"},
    {"artist": "Village People", "song": "Y.M.C.A.", "year": "1978", "hint": "Young man, there's no need to feel down"},
    {"artist": "Stevie Wonder", "song": "Superstition", "year": "1972", "hint": "Very superstitious, writing's on the wall"},
    {"artist": "Donna Summer", "song": "Hot Stuff", "year": "1979", "hint": "Looking for some hot stuff baby this evening"},
    {"artist": "KC and the Sunshine Band", "song": "That's the Way (I Like It)", "year": "1975", "hint": "Uh-huh, uh-huh, that's the way I like it"},
    {"artist": "The Jackson 5", "song": "ABC", "year": "1970", "hint": "Easy as 1 2 3, simple as do re mi"},
    {"artist": "Chic", "song": "Le Freak", "year": "1978", "hint": "Ah, freak out! Le freak, c'est chic"},
    {"artist": "Boney M.", "song": "Rasputin", "year": "1978", "hint": "Ra ra Rasputin, lover of the Russian queen"},
    {"artist": "Kool & The Gang", "song": "Celebration", "year": "1980", "hint": "Celebrate good times, come on!"},
    {"artist": "Sister Sledge", "song": "We Are Family", "year": "1979", "hint": "I got all my sisters with me"},
    {"artist": "The Trammps", "song": "Disco Inferno", "year": "1976", "hint": "Burn baby burn, disco inferno!"},
    {"artist": "Wild Cherry", "song": "Play That Funky Music", "year": "1976", "hint": "Play that funky music white boy"},
    # I: 16-30
    {"artist": "The Commodores", "song": "Brick House", "year": "1977", "hint": "She's mighty-mighty, just letting it all hang out"},
    {"artist": "Diana Ross", "song": "Upside Down", "year": "1980", "hint": "Boy, you turn me inside out and round and round"},
    {"artist": "Barry White", "song": "You're the First, the Last, My Everything", "year": "1974", "hint": "Deep romantic bass baritone spoken intro"},
    {"artist": "Marvin Gaye", "song": "Let's Get It On", "year": "1973", "hint": "I've been really tryin', baby"},
    {"artist": "The Temptations", "song": "Papa Was a Rollin' Stone", "year": "1972", "hint": "Wherever he laid his hat was his home"},
    {"artist": "Al Green", "song": "Let's Stay Together", "year": "1971", "hint": "Whether times are good or bad, happy or sad"},
    {"artist": "Baccara", "song": "Yes Sir, I Can Boogie", "year": "1977", "hint": "All night long"},
    {"artist": "Carl Douglas", "song": "Kung Fu Fighting", "year": "1974", "hint": "Those kicks were fast as lightning"},
    {"artist": "The O'Jays", "song": "Love Train", "year": "1972", "hint": "People all over the world, join hands"},
    {"artist": "Hot Chocolate", "song": "You Sexy Thing", "year": "1975", "hint": "I believe in miracles, where you from?"},
    {"artist": "Bee Gees", "song": "Night Fever", "year": "1977", "hint": "We know how to do it"},
    {"artist": "ABBA", "song": "Mamma Mia", "year": "1975", "hint": "Here I go again, my my, how can I resist you?"},
    {"artist": "Boney M.", "song": "Rivers of Babylon", "year": "1978", "hint": "By the rivers of Babylon, there we sat down"},
    {"artist": "Silver Convention", "song": "Fly, Robin, Fly", "year": "1975", "hint": "Up, up to the sky"},
    {"artist": "The Hues Corporation", "song": "Rock the Boat", "year": "1974", "hint": "Don't rock the boat baby, don't tip the boat over"},
    # N: 31-45
    {"artist": "Candi Staton", "song": "Young Hearts Run Free", "year": "1976", "hint": "Never be hung up, hung up like my man and me"},
    {"artist": "Anita Ward", "song": "Ring My Bell", "year": "1979", "hint": "You can ring my bell, ring my bell"},
    {"artist": "Amii Stewart", "song": "Knock on Wood", "year": "1979", "hint": "It's like thunder, lightning"},
    {"artist": "The Weather Girls", "song": "It's Raining Men", "year": "1982", "hint": "Hallelujah, it's raining men!"},
    {"artist": "Dan Hartman", "song": "Relight My Fire", "year": "1979", "hint": "Your love is like a flame"},
    {"artist": "Chic", "song": "Good Times", "year": "1979", "hint": "These are the good times, leave your cares behind"},
    {"artist": "Earth, Wind & Fire", "song": "Boogie Wonderland", "year": "1979", "hint": "Dance, boogie wonderland"},
    {"artist": "Kool & The Gang", "song": "Ladies' Night", "year": "1979", "hint": "Oh what a night!"},
    {"artist": "The Whispers", "song": "And the Beat Goes On", "year": "1979", "hint": "Just like my love everlasting"},
    {"artist": "ABBA", "song": "Gimme! Gimme! Gimme! (A Man After Midnight)", "year": "1979", "hint": "Won't somebody help me chase the shadows away"},
    {"artist": "Blondie", "song": "Heart of Glass", "year": "1978", "hint": "Once I had a love and it was a gas"},
    {"artist": "Rod Stewart", "song": "Da Ya Think I'm Sexy?", "year": "1978", "hint": "If you want my body and you think I'm sexy"},
    {"artist": "Barry Manilow", "song": "Copacabana (At the Copa)", "year": "1978", "hint": "Her name was Lola, she was a showgirl"},
    {"artist": "Leo Sayer", "song": "You Make Me Feel Like Dancing", "year": "1976", "hint": "Gonna dance the night away"},
    {"artist": "Andy Gibb", "song": "Shadow Dancing", "year": "1978", "hint": "How can I hold you when you're not even there?"},
    # G: 46-60
    {"artist": "Donna Summer", "song": "Bad Girls", "year": "1979", "hint": "Toot toot, hey, beep beep!"},
    {"artist": "Van McCoy", "song": "The Hustle", "year": "1975", "hint": "Do it! Do the hustle!"},
    {"artist": "Labelle", "song": "Lady Marmalade", "year": "1974", "hint": "Voulez-vous coucher avec moi ce soir?"},
    {"artist": "Peaches & Herb", "song": "Shake Your Groove Thing", "year": "1978", "hint": "Show 'em how we do it now"},
    {"artist": "Rose Royce", "song": "Car Wash", "year": "1976", "hint": "Working at the car wash, yeah"},
    {"artist": "The Real Thing", "song": "You to Me Are Everything", "year": "1976", "hint": "The sweetest song that I could sing, oh baby"},
    {"artist": "Heatwave", "song": "Boogie Nights", "year": "1976", "hint": "Ain't no doubt, we are here to party"},
    {"artist": "Tavares", "song": "Heaven Must Be Missing an Angel", "year": "1976", "hint": "'Cause you're here with me right now"},
    {"artist": "Maxine Nightingale", "song": "Right Back Where We Started From", "year": "1975", "hint": "It's love and you can't deny it"},
    {"artist": "Alicia Bridges", "song": "I Love the Nightlife", "year": "1978", "hint": "I got to boogie on the disco 'round"},
    {"artist": "Cheryl Lynn", "song": "Got to Be Real", "year": "1978", "hint": "What you find, what you feel, what you know"},
    {"artist": "Evelyn 'Champagne' King", "song": "Shame", "year": "1977", "hint": "Burning me up through my eyes"},
    {"artist": "The Sylvers", "song": "Boogie Fever", "year": "1975", "hint": "I got the boogie fever"},
    {"artist": "Vicki Sue Robinson", "song": "Turn the Beat Around", "year": "1976", "hint": "Love to hear percussion"},
    {"artist": "The Andrea True Connection", "song": "More, More, More", "year": "1976", "hint": "How do you like it? How do you like it?"},
    # O: 61-75
    {"artist": "Boney M.", "song": "Daddy Cool", "year": "1976", "hint": "She's crazy like a fool, what about it Daddy Cool?"},
    {"artist": "Ottawan", "song": "D.I.S.C.O.", "year": "1979", "hint": "She is D, delirious, she is I, incredible"},
    {"artist": "The Gibson Brothers", "song": "Cuba", "year": "1978", "hint": "Quiero bailar la salsa"},
    {"artist": "Lipps Inc.", "song": "Funkytown", "year": "1979", "hint": "Won't you take me to Funkytown?"},
    {"artist": "Yvonne Elliman", "song": "If I Can't Have You", "year": "1977", "hint": "I don't want nobody baby"},
    {"artist": "Samantha Sang", "song": "Emotion", "year": "1977", "hint": "It's just emotion that's taken me over"},
    {"artist": "The Ritchie Family", "song": "The Best Disco in Town", "year": "1976", "hint": "Groovy sounds on the dance floor"},
    {"artist": "Patrick Hernandez", "song": "Born to Be Alive", "year": "1979", "hint": "Yes we were born, born, born to be alive"},
    {"artist": "Village People", "song": "Macho Man", "year": "1978", "hint": "Every man wants to be a macho, macho man"},
    {"artist": "ABBA", "song": "Take a Chance on Me", "year": "1978", "hint": "If you change your mind, I'm the first in line"},
    {"artist": "Bee Gees", "song": "How Deep Is Your Love", "year": "1977", "hint": "I really mean to learn, 'cause we're living in a world of fools"},
    {"artist": "Earth, Wind & Fire", "song": "Shining Star", "year": "1975", "hint": "You're a shining star, no matter who you are"},
    {"artist": "George McCrae", "song": "Rock Your Baby", "year": "1974", "hint": "Take me in your arms"},
    {"artist": "The Miracles", "song": "Love Machine", "year": "1975", "hint": "I'm just a love machine, and I won't work for nobody but you"},
    {"artist": "The Spinners", "song": "Working My Way Back to You", "year": "1979", "hint": "I'll be loving you more and more each day"}
]
sets_data.append(make_music_set(10, "Golden 70s Disco Fever & Motown", "70s Disco", "music-70s", "Bell-bottoms, glitterballs, and studio 54 dancefloor funk from the 1970s.", "fa-record-vinyl", tracks_70s))

# Verification of all 10 sets
print(f"Total Sets Created: {len(sets_data)}")
for s in sets_data:
    print(f"Set {s['id']}: {s['name']} - Total Items: {len(s['items'])}")

# Write to JSON
with open("/home/jakes/repos/bingo/bingoSets.json", "w", encoding="utf-8") as f:
    json.dump(sets_data, f, indent=2, ensure_ascii=False)

# Write to JS (window.BINGO_SETS)
with open("/home/jakes/repos/bingo/bingoSets.js", "w", encoding="utf-8") as f:
    f.write("// TJ Entertainment @ Beerbox Midrand - Bingo Night Rotating Game Sets\n")
    f.write("window.BINGO_SETS = ")
    json.dump(sets_data, f, indent=2, ensure_ascii=False)
    f.write(";\n")

print("Successfully written bingoSets.json and bingoSets.js!")
